### ISSUE TITLE
access error in Fedora 41

### ISSUE THREAD

**Issue by nororon71** [Unrud/video-downloader#326]
OS: Fedora Linux 41 (Workstation Edition)

Libraries:
	Python 3.13.1
	GLib 2.82.2
	Gtk 4.16.5
	Libadwaita 1.6.2
	video-downloader 0.12.21
	yt-dlp 2024.12.23

Env:
	LANG=en_US.UTF-8
	
	ERROR: unable to download video data: HTTP Error 403: Forbidden

if I use commandline yt-dlp the downloading working

**Comment by sitaramdas73** [comment]
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by meidaid** [comment]
I noticed this problem starting today.  About 24 to 48 hours earlier I had no trouble at all.

**Comment by bbharland** [comment]
I'm having the same problem.  Downloading the latest stable yt-dlp fixes the issue, but isn't in the Fedora repository yet?

OS: Fedora Linux 41 (KDE Plasma)

Libraries:
	Python 3.13.1
	GLib 2.82.2
	Gtk 4.16.5
	Libadwaita 1.6.2
	video-downloader 0.12.21
	yt-dlp 2024.12.23

Env:
	LANG=en_US.UTF-8

**Comment by katian** [comment]
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by bbharland** [comment]
Fedora included yt-dlp-0:2025.01.12-1 in this morning's update.  This should fix this issue.  (It did for me)

**Comment by orgonangel** [comment]
Hi everyone,

I’m having trouble with a video downloader on Ubuntu 22.04.5 LTS and could really use some help. The app doesn’t appear in the Snap Store, so I had to install it through the terminal. I recently upgraded it, but it still isn’t working properly.

Does anyone know how to fix this or what steps I might be missing? Any advice would be greatly appreciated!

Thanks in advance! 😊

**Comment by meidaid** [comment]
> Hi everyone,
> 
> I’m having trouble with a video downloader on Ubuntu 22.04.5 LTS and could really use some help. The app doesn’t appear in the Snap Store, so I had to install it through the terminal. I recently upgraded it, but it still isn’t working properly.
> 
> Does anyone know how to fix this or what steps I might be missing? Any advice would be greatly appreciated!
> 
> Thanks in advance! 😊

Hello, @orgonangel !

I just checked the snap package both the online Snap Store as well as the Ubuntu Software application in Ubuntu Linux 22.04.5 LTS and found that it is listed in both cases.  I've added the screenshots below.

What I do know is that the latest/stable version 0.12.21 is the one that is having troubles right now.  It would appear that we might have to wait for a new stable to be released  through the pipeline.  (I only use stable releases, so I have to wait).

![Screenshot from 2025-01-16 06-57-43](https://github.com/user-attachments/assets/f5c13163-2200-403f-bdd8-375203bf6e51)
![Screenshot from 2025-01-16 07-00-04](https://github.com/user-attachments/assets/b079732e-a12d-476b-baac-526cf1d0a9b2)

**Comment by katian** [comment]
```
$ snap info video-downloader 
name:      video-downloader
summary:   Download web videos
publisher: unrud
store-url: https://snapcraft.io/video-downloader
contact:   https://github.com/Unrud/video-downloader/issues
license:   GPL-3.0+
description: |
  Download videos from websites with an easy-to-use interface.
  Provides the following features:
  
  
  - Convert videos to MP3
  - Supports password-protected and private videos
  - Download single videos or whole playlists
  - Automatically selects a video format based on your quality demands
  
  
  Based on yt-dlp.
commands:
  - video-downloader
snap-id:      4qIOUqXVjsMokMAzzlIcP7lrUUdwtKS3
tracking:     latest/stable
refresh-date: hier à 06 h 8 HNR
channels:
  latest/stable:    0.12.21 2024-12-26 (1233) 27MB -
  latest/candidate: ↑                              
  latest/beta:      ↑                              
  latest/edge:      0.12.22 2025-01-13 (1238) 27MB -
installed:          0.12.21            (1233) 27MB -

```

**Comment by orgonangel** [comment]
Thank you very much for the help. I guess I'll have to wait untill the stable version is released.
Kind Regards

**Comment by nororon71** [comment]
Updating and loading repositories:
Repositories loaded.
Package "yt-dlp-2025.01.12-1.fc41.noarch" is already installed.
Nothing to do.

And now I have next error:   **ERROR: Error opening output files: Encoder not found**

![Image](https://github.com/user-attachments/assets/b5cfb2e8-e61d-4954-898f-0b62ef41f18c)

**Comment by meidaid** [comment]
😃 Good news everyone!  It appears that @Unrud  has released a fixed package!

I just refreshed and there is a NEW package for video-downloader available, **version 0.12.22**:

```
$ sudo snap refresh video-downloader
video-downloader 0.12.22 from unrud refreshed
```

This is the **stable** version!

I just did some light testing and it seems to work!

I will keep testing it, but I am sure that since so many people were waiting for this to be working again that it would be really great if others tested it and reported back here if it is working for them or not as well.  😃

**Comment by katian** [comment]
it works ❤ thanks a lot !

**Comment by orgonangel** [comment]
Just updated Video Downloader in Ubuntu and everything is back to normal.

**Comment by nororon71** [comment]
...
> $ sudo snap refresh video-downloader
> video-downloader 0.12.22 from unrud refreshed
> ```
...
Thanks for help now is working again
